export const Currencies = [
    'USD',
    'EUR',
    'JPY',
    'CNY',
    'HKD',
    'TWD',
    'GBP',
    'OMR',
    'CAD',
    'CHF',
    'SEK',
    'AUD',
    'NZD',
    'CZK',
    'CLP',
    'TRY',
    'MNT',
    'ILS',
    'DKK',
    'NOK',
    'SAR',
    'KWD',
    'BHD',
    'AED',
    'JOD',
    'EGP',
    'THB',
    'SGD',
    'MYR',
    'IDR',
    'QAR',
    'KZT',
    'BND',
    'INR',
    'PKR',
    'BDT',
    'PHP',
    'MXN',
    'BRL',
    'VND',
    'RUB',
    'HUF',
    'PLN',
    'LKR',
    'DZD',
    'KES',
    'COP',
    'TZS',
    'NPR',
    'RON',
    'LYD',
    'MOP',
    'MMK',
    'ETB',
    'UZS',
    'KHR',
    'FJD',
] as const

export const CurrenciesMap = {
    USD: { EN: 'US Dollar', KO: '달러', JP: 'ドル' },
    EUR: { EN: 'Euro', KO: '유로', JP: 'ユーロ' },
    JPY: { EN: 'Japanese Yen', KO: '엔', JP: '円' },
    CNY: { EN: 'Chinese Yuan', KO: '위안', JP: '元' },
    HKD: { EN: 'Hong Kong Dollar', KO: '홍콩 달러', JP: '香港ドル' },
    TWD: { EN: 'New Taiwan Dollar', KO: '대만 달러', JP: 'ニュー台湾ドル' },
    GBP: { EN: 'British Pound', KO: '파운드', JP: 'ポンド' },
    OMR: { EN: 'Omani Rial', KO: '오만 리알', JP: 'オマーン・リアル' },
    CAD: { EN: 'Canadian Dollar', KO: '캐나다 달러', JP: 'カナダドル' },
    CHF: { EN: 'Swiss Franc', KO: '스위스 프랑', JP: 'スイスフラン' },
    SEK: { EN: 'Swedish Krona', KO: '스웨덴 크로나', JP: 'スウェーデンクローナ' },
    AUD: { EN: 'Australian Dollar', KO: '호주 달러', JP: '豪ドル' },
    NZD: { EN: 'New Zealand Dollar', KO: '뉴질랜드 달러', JP: 'ニュージーランドドル' },
    CZK: { EN: 'Czech Koruna', KO: '체코 코루나', JP: 'チェコ・コルナ' },
    CLP: { EN: 'Chilean Peso', KO: '칠레 페소', JP: 'チリペソ' },
    TRY: { EN: 'Turkish Lira', KO: '터키 리라', JP: 'トルコリラ' },
    MNT: { EN: 'Mongolian Tögrög', KO: '몽골 투그릭', JP: 'モンゴルトゥグリク' },
    ILS: { EN: 'Israeli New Shekel', KO: '이스라엘 셰켈', JP: 'イスラエル新シェケル' },
    DKK: { EN: 'Danish Krone', KO: '덴마크 크로네', JP: 'デンマーククローネ' },
    NOK: { EN: 'Norwegian Krone', KO: '노르웨이 크로네', JP: 'ノルウェークローネ' },
    SAR: { EN: 'Saudi Riyal', KO: '사우디 리얄', JP: 'サウジリヤル' },
    KWD: { EN: 'Kuwaiti Dinar', KO: '쿠웨이트 디나르', JP: 'クウェート・ディナール' },
    BHD: { EN: 'Bahraini Dinar', KO: '바레인 디나르', JP: 'バーレーン・ディナール' },
    AED: { EN: 'United Arab Emirates Dirham', KO: '아랍에미리트 디르함', JP: 'UAEディルハム' },
    JOD: { EN: 'Jordanian Dinar', KO: '요르단 디나르', JP: 'ヨルダン・ディナール' },
    EGP: { EN: 'Egyptian Pound', KO: '이집트 파운드', JP: 'エジプトポンド' },
    THB: { EN: 'Thai Baht', KO: '태국 바트', JP: 'タイバーツ' },
    SGD: { EN: 'Singapore Dollar', KO: '싱가포르 달러', JP: 'シンガポールドル' },
    MYR: { EN: 'Malaysian Ringgit', KO: '말레이시아 링깃', JP: 'マレーシアリンギット' },
    IDR: { EN: 'Indonesian Rupiah', KO: '인도네시아 루피아', JP: 'インドネシアルピア' },
    QAR: { EN: 'Qatari Riyal', KO: '카타르 리얄', JP: 'カタールリヤル' },
    KZT: { EN: 'Kazakhstani Tenge', KO: '카자흐스탄 텡게', JP: 'カザフスタンテンゲ' },
    BND: { EN: 'Brunei Dollar', KO: '브루나이 달러', JP: 'ブルネイドル' },
    INR: { EN: 'Indian Rupee', KO: '인도 루피', JP: 'インドルピー' },
    PKR: { EN: 'Pakistani Rupee', KO: '파키스탄 루피', JP: 'パキスタンルピー' },
    BDT: { EN: 'Bangladeshi Taka', KO: '방글라데시 타카', JP: 'バングラデシュタカ' },
    PHP: { EN: 'Philippine Peso', KO: '필리핀 페소', JP: 'フィリピンペソ' },
    MXN: { EN: 'Mexican Peso', KO: '멕시코 페소', JP: 'メキシコペソ' },
    BRL: { EN: 'Brazilian Real', KO: '브라질 헤알', JP: 'ブラジルレアル' },
    VND: { EN: 'Vietnamese Dong', KO: '베트남 동', JP: 'ベトナムドン' },
    RUB: { EN: 'Russian Ruble', KO: '러시아 루블', JP: 'ロシアルーブル' },
    HUF: { EN: 'Hungarian Forint', KO: '헝가리 포린트', JP: 'ハンガリーフォリント' },
    PLN: { EN: 'Polish Zloty', KO: '폴란드 즈워티', JP: 'ポーランドズロチ' },
    LKR: { EN: 'Sri Lankan Rupee', KO: '스리랑카 루피', JP: 'スリランカルピー' },
    DZD: { EN: 'Algerian Dinar', KO: '알제리 디나르', JP: 'アルジェリアディナール' },
    KES: { EN: 'Kenyan Shilling', KO: '케냐 실링', JP: 'ケニアシリング' },
    COP: { EN: 'Colombian Peso', KO: '콜롬비아 페소', JP: 'コロンビアペソ' },
    TZS: { EN: 'Tanzanian Shilling', KO: '탄자니아 실링', JP: 'タンザニアシリング' },
    NPR: { EN: 'Nepalese Rupee', KO: '네팔 루피', JP: 'ネパールルピー' },
    RON: { EN: 'Romanian Leu', KO: '루마니아 레우', JP: 'ルーマニアレウ' },
    LYD: { EN: 'Libyan Dinar', KO: '리비아 디나르', JP: 'リビアディナール' },
    MOP: { EN: 'Macanese Pataca', KO: '마카오 파타카', JP: 'マカオパタカ' },
    MMK: { EN: 'Myanmar Kyat', KO: '미얀마 짯', JP: 'ミャンマーチャット' },
    ETB: { EN: 'Ethiopian Birr', KO: '에티오피아 비르', JP: 'エチオピアブル' },
    UZS: { EN: 'Uzbekistani Som', KO: '우즈베키스탄 솜', JP: 'ウズベキスタンソム' },
    KHR: { EN: 'Cambodian Riel', KO: '캄보디아 리엘', JP: 'カンボジアリエル' },
    FJD: { EN: 'Fijian Dollar', KO: '피지 달러', JP: 'フィジードル' },
} as const

export type CurrencyCode = keyof typeof CurrenciesMap
export type CurrencyTranslations = (typeof CurrenciesMap)[CurrencyCode]
