export const Currencies = [
    'KRW',
    'USD',
    'EUR',
    'JPY',
    'HKD',
    'TWD',
    'GBP',
    'CAD',
    'CHF',
    'SEK',
    'AUD',
    'NZD',
    'DKK',
    'AED',
    'THB',
    'SGD',
    'MYR',
    'IDR',
    'INR',
    'PKR',
    'PHP',
    'BRL',
    'CNY',
] as const

export const CurrenciesMap = {
    KRW: { EN: 'Korean Won', KO: '원', JP: '韓国ウォン' },
    USD: { EN: 'US Dollar', KO: '달러', JP: 'ドル' },
    EUR: { EN: 'Euro', KO: '유로', JP: 'ユーロ' },
    JPY: { EN: 'Japanese Yen', KO: '엔', JP: '円' },
    HKD: { EN: 'Hong Kong Dollar', KO: '홍콩 달러', JP: '香港ドル' },
    TWD: { EN: 'New Taiwan Dollar', KO: '대만 달러', JP: 'ニュー台湾ドル' },
    GBP: { EN: 'British Pound', KO: '파운드', JP: 'ポンド' },
    CAD: { EN: 'Canadian Dollar', KO: '캐나다 달러', JP: 'カナダドル' },
    CHF: { EN: 'Swiss Franc', KO: '스위스 프랑', JP: 'スイスフラン' },
    SEK: { EN: 'Swedish Krona', KO: '스웨덴 크로나', JP: 'スウェーデンクローナ' },
    AUD: { EN: 'Australian Dollar', KO: '호주 달러', JP: '豪ドル' },
    NZD: { EN: 'New Zealand Dollar', KO: '뉴질랜드 달러', JP: 'ニュージーランドドル' },
    DKK: { EN: 'Danish Krone', KO: '덴마크 크로네', JP: 'デンマーククローネ' },
    AED: { EN: 'United Arab Emirates Dirham', KO: '아랍에미리트 디르함', JP: 'UAEディルハム' },
    THB: { EN: 'Thai Baht', KO: '태국 바트', JP: 'タイバーツ' },
    SGD: { EN: 'Singapore Dollar', KO: '싱가포르 달러', JP: 'シンガポールドル' },
    MYR: { EN: 'Malaysian Ringgit', KO: '말레이시아 링깃', JP: 'マレーシアリンギット' },
    IDR: { EN: 'Indonesian Rupiah', KO: '인도네시아 루피아', JP: 'インドネシアルピア' },
    INR: { EN: 'Indian Rupee', KO: '인도 루피', JP: 'インドルピー' },
    PKR: { EN: 'Pakistani Rupee', KO: '파키스탄 루피', JP: 'パキスタンルピー' },
    PHP: { EN: 'Philippine Peso', KO: '필리핀 페소', JP: 'フィリピンペソ' },
    BRL: { EN: 'Brazilian Real', KO: '브라질 헤알', JP: 'ブラジルレアル' },
    CNY: { EN: 'Chinese Yuan', KO: '위안', JP: '元' },
} as const
