name: Release
on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - created

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: create dotenv
      run: |
        touch ./src/assets/.env
        echo "API_URL=${{ secrets.API_URL }}" >> ./src/assets/.env
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run pub